### ISSUE TITLE
Inconsistent API

### ISSUE THREAD

**Issue by katsaii** [jack27121/STANNcam#2]
Glancing at the source code to this library, I immediately notice the definitions inside of `stanncam_functions`. I am assuming these are the user-facing parts of your library; if so, it would be a good idea to have a consistent naming convention for them to make discoverability easier, and avoid naming conflicts.

For example, sometimes you use `cam` (in `cam_x` and `cam_y`), but then switch to `camera` other times (in `camera_zoom`).

My suggestion is to refactor the functions to these names:
```
toggle_fullscreen          ->  stanncam_toggle_fullscreen
resolution_update          ->  stanncam_update_resolution
screen_shake               ->  stanncam_add_screen_shake
camera_move                ->  stanncam_move
camera_zoom                ->  stanncam_zoom
cam_x                      ->  stanncam_x
cam_y                      ->  stanncam_y
out_cam_bounds             ->  stanncam_out_of_bounds
point_in_rectangle_camera  ->  stanncam_point_in_rectangle
room_to_gui_x              ->  stanncam_room_to_gui_x
room_to_gui_y              ->  stanncam_room_to_gui_y
```

**Comment by jack27121** [comment]
Thanks for the feedback. I will get around to this

**Comment by jack27121** [comment]
This has been changed in the newest release https://github.com/jack27121/STANNcam/releases/tag/v1.0.0
