### ISSUE TITLE
Unnecessary GitGuardian Security Checks

### ISSUE THREAD

**Issue by bfrymire** [jack27121/STANNcam#50]
GameMaker in general and a camera library like STANNcam does not use secrets, making the GitGuardian Security Checks unneeded.

**Comment by jack27121** [comment]
i've no idea what that is, i'm up for removing it, but i don't know how 😬 Where is it?

**Comment by bfrymire** [comment]
Look in the [Security tab](https://github.com/jack27121/STANNcam/security) on the repo.

**Comment by jack27121** [comment]
there's no such option to turn it off

**Comment by jack27121** [comment]
scratch that, it was in user settings, not repo settings. It's off now
