### ISSUE TITLE
"Smeared" surface at the bottom when scrolling down

### ISSUE THREAD

**Issue by oliverhermanni** [jack27121/STANNcam#71]
When I scroll down in my game there's a smear effect at the bottom of window.

![image](https://github.com/jack27121/STANNcam/assets/1240179/f48e1eb3-5618-4680-a8c0-0ba319a29b67)
There should be a black line at the bottom of the wall, as you can see some pixels above.

![image](https://github.com/jack27121/STANNcam/assets/1240179/fbcf8e5d-73a9-41d1-a593-1ebc133b0a34)
Here you can see the effect even better.

 It wouldn't be that bad if I use pixel perfect scrolling, but my character moves in a smooth grid, so it's very visible while playing.

Any way to prevent this smear effect? I probably could overlay it with my GUI, but I'd rather have the effect gone.

**Comment by jack27121** [comment]
seems and sounds like a bug, will fix it when i can

**Comment by jack27121** [comment]
https://github.com/jack27121/STANNcam/releases/tag/v2.3.1 now released @oliverhermanni
